import Navbar from 'layout/header/navbar'
import '../styles/globals.scss'
import type {Metadata} from 'next'
import {Merriweather} from 'next/font/google'
import {Roboto} from 'next/font/google'

// primary font
const merriweather = Merriweather({
  subsets: ['latin'],
  weight: ['300', '400', '700', '900'],
  style: ['normal'],
  display: 'swap',
  variable: '--font-secondary',
})

// Secondary font
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  style: ['normal'],
  display: 'swap',
  variable: '--font-primary',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${roboto.variable} ${merriweather.variable}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  )
}
